# Generated by Django 3.2.9 on 2023-03-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0002_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.CharField(choices=[('monthly', 600), ('quaterly', 1500), ('half_yearly', 2500), ('yearly', 5000)], default=None, max_length=12),
        ),
    ]
