# Generated by Django 3.2.9 on 2023-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0003_alter_member_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
